### ISSUE TITLE
@export missing from docs in impute.R

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/tidyplusR#28]
@export missing from docs in impute.R and this leads to user not being able to call function:
```
> impute(dat,method = "mean")
Error in impute(dat, method = "mean") : could not find function "impute"
```

**Comment by akshi8** [comment]
Fixed: https://github.com/UBC-MDS/tidyplusR/commit/79a7f8a1c6dfab2a818fccb46a93db07e5c89955
