### ISSUE TITLE
tests not passing

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/tidyplusR#31]
Tried to run your tests with `devtools::test()` and 2 failed and there was 1 warning:

```
> devtools::test()
Loading tidyplusR
Loading required package: testthat
Testing tidyplusR
✔ | OK F W S | Context
Error in x[[method]](...) : attempt to apply non-function

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════
OK:       0
Failed:   2
Warnings: 1
Skipped:  0

Keep trying!
```

**Comment by ttimbers** [comment]
Also - why does it look like only 3 tests are being run? You have more than 3 tests in your `tests` directory...

**Comment by ttimbers** [comment]
This problem also prevents me from running `covr::reports` to assess your test coverage:

```
> covr::report()
Error: Failure in `/private/var/folders/9w/mzjb0_j118vd2k4762ggh43w0000gn/T/RtmpneQOnT/R_LIBSff707747be48/tidyplusR/tidyplusR-tests/testthat.Rout.fail`
> library(testthat)
> library(tidyplusR)
> 
> test_check("tidyplusR")
── 1. Error: (unknown) (@test_impute.R#5)  ───────────────────────────────────────────────────────────────────────────
`path` does not exist
1: testthat::test_file("impute.R") at testthat/test_impute.R:5
2: stop("`path` does not exist", call. = FALSE)

══ testthat results  ═════════════════════════════════════════════════════════════════════════════════════════════════
OK: 127 SKIPPED: 0 FAIL
```

**Comment by ttimbers** [comment]
As well as `goodpractice::gp()` to identify likely sources of errors and style issues. Once you fix the tests so they run you should try to run these functions to identify ways to further improve your package.

**Comment by akshi8** [comment]
@ttimbers 
Thanks a lot, will test these with `goodpractice::gp()`. I suppose most path, function call errors have occurred for other users and didn't show up for us. We'll do thorough testing this time

**Comment by xinbinhuang** [comment]
Package check passed 
549975f56f286dd88e40f688e574204860d2960f
